# -*- coding: utf-8 -*-
"""hand digit recognition using logistic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vccGI9dAKAj_id2zCXdyxczlXpVsJT5m
"""

from sklearn.datasets import fetch_openml

mnist=fetch_openml('mnist_784')



temp=x[95]
temp.shape



y[95]




model.fit(xtrain,ytrain)

model.score(xtrain,ytrain)

model.score(xtest,ytest)

