# -*- coding: utf-8 -*-
"""hand digit recognition using logistic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vccGI9dAKAj_id2zCXdyxczlXpVsJT5m
"""

from sklearn.datasets import fetch_openml

mnist=fetch_openml('mnist_784')

# Assign X and Y values
x=mnist.data.values
y=mnist.target

temp=x[95]
temp.shape

# Importing matplotlib

import matplotlib.pyplot as plt

plt.imshow(temp.reshape(28,28)) 

y[95]

# import train test split

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=10)


model.fit(xtrain,ytrain)

model.score(xtrain,ytrain)

model.score(xtest,ytest)

